export interface HelpItem {
  id: string;
  title: string;
  category: 'agenda' | 'prontuario' | 'avaliacao' | 'financeiro' | 'fiscal' | 'configuracoes' | 'geral' | string;
  description: string;
  clinicalAndLegalTip: string;
  bestPractice?: string;
  howToUse?: string;
  iconName?: string;
  isAiGenerated?: boolean;
}

export const CATEGORY_LABELS: Record<HelpItem['category'], { label: string; color: string }> = {
  agenda: {
    label: 'Agenda & Atendimentos',
    color: 'bg-teal-100 text-teal-800 border-teal-300 dark:bg-teal-950/80 dark:text-teal-300 dark:border-teal-700',
  },
  prontuario: {
    label: 'Prontuário & Ética CFP',
    color: 'bg-emerald-100 text-emerald-800 border-emerald-300 dark:bg-emerald-950/80 dark:text-emerald-300 dark:border-emerald-700',
  },
  avaliacao: {
    label: 'Avaliação Neuropsicológica',
    color: 'bg-purple-100 text-purple-800 border-purple-300 dark:bg-purple-950/80 dark:text-purple-300 dark:border-purple-700',
  },
  financeiro: {
    label: 'Financeiro & Honorários',
    color: 'bg-blue-100 text-blue-800 border-blue-300 dark:bg-blue-950/80 dark:text-blue-300 dark:border-blue-700',
  },
  fiscal: {
    label: 'Contabilidade, NFs & DARF',
    color: 'bg-amber-100 text-amber-800 border-amber-300 dark:bg-amber-950/80 dark:text-amber-300 dark:border-amber-700',
  },
  configuracoes: {
    label: 'Segurança & RBAC',
    color: 'bg-rose-100 text-rose-800 border-rose-300 dark:bg-rose-950/80 dark:text-rose-300 dark:border-rose-700',
  },
  geral: {
    label: 'Navegação do Sistema',
    color: 'bg-slate-100 text-slate-800 border-slate-300 dark:bg-slate-800 dark:text-slate-200 dark:border-slate-700',
  },
};

export const INSPECTOR_ITEMS: Record<string, HelpItem> = {
  'generic-readonly-notice': {
    id: 'generic-readonly-notice',
    title: 'Ambiente de Ajuda (Somente Leitura)',
    category: 'geral',
    description: 'Enquanto o Modo de Ajuda estiver ativo, ações e edições de dados ficam estritamente bloqueadas para proteger as informações da clínica contra mutações acidentais.',
    clinicalAndLegalTip: 'O modo somente leitura garante a inviolabilidade ética dos prontuários (Resolução CFP 06/2019) e dos lançamentos contábeis durante a exploração do sistema.',
    bestPractice: 'Você pode navegar normalmente entre as telas pela barra lateral. Para voltar a editar ou salvar dados, encerre o modo clicando em "Sair da Ajuda" ou pressionando a tecla ESC.',
    iconName: 'Shield',
  },
  'header-help-btn': {
    id: 'header-help-btn',
    title: 'Modo Inspetor de Ajuda',
    category: 'geral',
    description: 'Ativa o modo de inspeção visual contextual. Permite clicar em qualquer botão, aba, filtro ou tabela do sistema para compreender sua utilidade e embasamento clínico/legal.',
    clinicalAndLegalTip: 'Projetado para facilitar o onboarding de profissionais da clínica e garantir conformidade com os fluxos operacionais e éticos do CFP.',
    bestPractice: 'Você pode fechar o card ou o inspetor a qualquer momento pressionando a tecla ESC.',
    iconName: 'HelpCircle',
  },
  'header-theme-toggle': {
    id: 'header-theme-toggle',
    title: 'Alternador de Tema (Claro / Escuro)',
    category: 'geral',
    description: 'Alterna a interface entre os modos claro e escuro de alto contraste.',
    clinicalAndLegalTip: 'O modo escuro reduz a emissão de luz azul e a fadiga ocular durante longas jornadas de escrita de prontuários, laudos e fechamentos financeiros noturnos.',
    bestPractice: 'A preferência escolhida fica salva automaticamente no navegador.',
    iconName: 'Sun',
  },
  'header-rbac-switcher': {
    id: 'header-rbac-switcher',
    title: 'Simulador de Perfis (RBAC & LGPD)',
    category: 'configuracoes',
    description: 'Permite alternar instantaneamente entre os perfis de Psicólogo Clínico, Secretária e Administrador para validar permissões de acesso.',
    clinicalAndLegalTip: 'Atende ao Art. 11 da LGPD e ao Código de Ética do Psicólogo: secretárias não têm acesso aos registros clínicos confidenciais e prontuários; apenas psicólogos habilitados com CRP podem consultar e evoluir pacientes.',
    bestPractice: 'Utilize esta ferramenta para verificar exatamente o que recepcionistas e parceiros visualizam em cada tela.',
    iconName: 'Sparkles',
  },
  'header-user-profile': {
    id: 'header-user-profile',
    title: 'Identificação Profissional & CRP',
    category: 'prontuario',
    description: 'Exibe o nome do profissional conectado, número do registro no Conselho Regional de Psicologia (CRP) e nível de privilégio.',
    clinicalAndLegalTip: 'Conforme a Resolução CFP nº 06/2019, toda intervenção e documento psicológico deve conter de forma indelével a identificação e o CRP do profissional responsável.',
    bestPractice: 'Mantenha o número de CRP devidamente cadastrado no Perfil para emissão automática de laudos e declarações.',
    iconName: 'ShieldCheck',
  },
  'header-logout': {
    id: 'header-logout',
    title: 'Encerramento Seguro de Sessão',
    category: 'configuracoes',
    description: 'Encerra a sessão ativa do usuário e remove os tokens de autenticação da memória.',
    clinicalAndLegalTip: 'Essencial em computadores compartilhados da recepção ou consultório para evitar que terceiros visualizem dados sensíveis de pacientes (Art. 46 da LGPD).',
    bestPractice: 'Sempre encerre a sessão ao se ausentar da sala de atendimento.',
    iconName: 'LogOut',
  },
  'agenda-view-selector': {
    id: 'agenda-view-selector',
    title: 'Visões da Agenda Clínica',
    category: 'agenda',
    description: 'Permite alternar entre as visualizações Mensal, Semanal, Diária e em Lista.',
    clinicalAndLegalTip: 'A gestão visual de horários evita sobreposição de atendimentos e preserva o intervalo recomendado entre sessões para acolhimento e anotação imediata da evolução.',
    bestPractice: 'A visão diária é ideal para focar nas chegadas e na recepção dos pacientes do dia.',
    iconName: 'Calendar',
  },
  'agenda-status-filter': {
    id: 'agenda-status-filter',
    title: 'Filtros de Status de Atendimento',
    category: 'agenda',
    description: 'Filtra os atendimentos por Agendado, Confirmado, Realizado, Falta Justificada ou Cancelado.',
    clinicalAndLegalTip: 'O controle rigoroso de faltas e presenças é fundamental para respaldar a cobrança de honorários de sessões reservadas e acompanhar a assiduidade terapêutica.',
    bestPractice: 'Marque como Concluído logo após o término da sessão para liberar a respectiva baixa financeira.',
    iconName: 'Filter',
  },
  'agenda-new-session': {
    id: 'agenda-new-session',
    title: 'Novo Agendamento Clínico',
    category: 'agenda',
    description: 'Abre o formulário de reserva de horário para Psicoterapia Individual, Avaliação Neuropsicológica ou Devolutiva.',
    clinicalAndLegalTip: 'Define o tipo de atendimento, modalidade (Presencial ou Online) e valores acordados no enquadre terapêutico inicial.',
    bestPractice: 'Verifique se o paciente já tem cadastro ativo para vincular automaticamente ao prontuário histórico.',
    iconName: 'Plus',
  },
  'prontuario-evolution': {
    id: 'prontuario-evolution',
    title: 'Evolução Clínica Ética (CFP 06/2019)',
    category: 'prontuario',
    description: 'Registro cronológico do atendimento contendo descrição da demanda, intervenções técnicas adotadas e encaminhamentos.',
    clinicalAndLegalTip: 'Obrigatório pela Resolução CFP nº 06/2019. Deve ser mantido por no mínimo 5 anos após o término do acompanhamento, sob estrito sigilo profissional.',
    bestPractice: 'Redija as anotações mantendo linguagem técnica, objetiva e respeitando o sigilo de terceiros envolvidos.',
    iconName: 'FileText',
  },
  'prontuario-sha256': {
    id: 'prontuario-sha256',
    title: 'Assinatura Digital & Hash SHA-256',
    category: 'prontuario',
    description: 'Gera uma assinatura criptográfica imutável para cada evolução salva, comprovando a autoria e data/hora exatas.',
    clinicalAndLegalTip: 'Garante a autenticidade e a não-adulteração retroativa do prontuário perante auditorias do Conselho de Psicologia, operadoras de saúde e processos judiciais.',
    bestPractice: 'Uma vez assinada, a evolução não pode ser reescrita; complementações devem ser feitas via aditamento datado.',
    iconName: 'Lock',
  },
  'prontuario-confidential': {
    id: 'prontuario-confidential',
    title: 'Anotações Pessoais Confidenciais',
    category: 'prontuario',
    description: 'Espaço restrito para hipóteses diagnósticas preliminares e impressões íntimas do psicólogo assistente.',
    clinicalAndLegalTip: 'Protegidas pela Resolução CFP 06/2019: não integram a folha pública do prontuário entregue ao paciente em caso de solicitação de cópia de registros.',
    bestPractice: 'Use para rascunhos de transferência e hipóteses de trabalho da supervisão clínica.',
    iconName: 'Shield',
  },
  'avaliacao-bateria': {
    id: 'avaliacao-bateria',
    title: 'Bateria de Testes Neuropsicológicos',
    category: 'avaliacao',
    description: 'Gestão e tabulação de instrumentos psicométricos privativos com cálculo de percentis, escores Z e tabelas normativas.',
    clinicalAndLegalTip: 'Todo instrumento utilizado deve possuir parecer favorável no SATEPSI do CFP. Testes desfavoráveis invalidam a perícia e o laudo.',
    bestPractice: 'Confira as tabelas normativas de escolaridade e idade antes de transcrever os escores brutos.',
    iconName: 'Brain',
  },
  'avaliacao-laudo': {
    id: 'avaliacao-laudo',
    title: 'Laudo Neuropsicológico Estruturado',
    category: 'avaliacao',
    description: 'Gerador do documento técnico pericial contendo Identificação, Descrição da Demanda, Procedimento, Análise Quali-Quantitativa e Conclusão.',
    clinicalAndLegalTip: 'Estruturado rigorosamente segundo o Art. 13 da Resolução CFP nº 06/2019. Deve conter fundamentação técnico-científica e linguagem compreensível aos solicitantes.',
    bestPractice: 'Revise o capítulo de Conclusão e Encaminhamentos garantindo que responda explicitamente ao objetivo da queixa inicial.',
    iconName: 'FileCheck',
  },
  'nf-solicitacoes-tab': {
    id: 'nf-solicitacoes-tab',
    title: 'Painel para Solicitações de Nota Fiscal',
    category: 'fiscal',
    description: 'Fila de pedidos de emissão de NF aguardando encaminhamento ou transmissão para a contabilidade da clínica.',
    clinicalAndLegalTip: 'Sessões quitadas pelo paciente que exigem nota fiscal de serviços de saúde devem ser apuradas aqui para escrituração fiscal mensal.',
    bestPractice: 'Filtre por tipo de atendimento para enviar à contabilidade lotes específicos de Psicoterapia ou Avaliação.',
    iconName: 'Receipt',
  },
  'nf-emitidas-tab': {
    id: 'nf-emitidas-tab',
    title: 'Painel de Notas Fiscais Emitidas',
    category: 'fiscal',
    description: 'Histórico consolidado de notas fiscais geradas, autorizadas ou canceladas pela prefeitura e contabilidade.',
    clinicalAndLegalTip: 'Permite acompanhar o número da NF, link de consulta, data de competência e valor total apurado para cruzamento contábil e IRPF.',
    bestPractice: 'Utilize os filtros rápidos de data e modalidade para conciliar com os extratos bancários.',
    iconName: 'CheckCircle',
  },
  'nf-filter-service-type': {
    id: 'nf-filter-service-type',
    title: 'Filtro por Tipo de Atendimento',
    category: 'fiscal',
    description: 'Segmenta as notas fiscais entre Sessões de Psicoterapia (atendimentos contínuos) e Avaliações Neuropsicológicas (projetos periciais fechados).',
    clinicalAndLegalTip: 'Psicoterapia e Avaliação frequentemente possuem descrições de serviços fiscais (CNAE/LC 116) e faixas de precificação distintas para declaração no IRPF/DMED.',
    bestPractice: 'Facilita a prestação de contas separada para pacientes que realizam tanto terapia quanto avaliação na clínica.',
    iconName: 'Filter',
  },
  'carne-leao-export': {
    id: 'carne-leao-export',
    title: 'Livro Caixa & Carnê-Leão (DARF 0190)',
    category: 'fiscal',
    description: 'Relatório formatado com o CPF do titular pagador, beneficiário e valores recebidos, pronto para importação no portal e-CAC da Receita Federal.',
    clinicalAndLegalTip: 'Psicólogos autônomos são obrigados a escriturar o Livro Caixa e recolher o imposto de renda mensalmente pelo Carnê-Leão (Código de Receita 0190) para receitas de pessoas físicas.',
    bestPractice: 'Exporte mensalmente até o último dia útil para calcular o recolhimento tempestivo sem multas de mora.',
    iconName: 'FileSpreadsheet',
  },
  'repasse-panel': {
    id: 'repasse-panel',
    title: 'Gestão de Repasses aos Psicólogos',
    category: 'financeiro',
    description: 'Cálculo automatizado do percentual de divisão de honorários entre a clínica e os profissionais parceiros (sublocação ou porcentagem contratual).',
    clinicalAndLegalTip: 'Garante transparência na remuneração dos membros da equipe e evita bi-tributação sobre receitas repassadas a pessoas jurídicas ou autônomos.',
    bestPractice: 'Realize o fechamento semanal ou quinzenal gerando o recibo detalhado para assinatura dos parceiros.',
    iconName: 'Coins',
  },
  'financial-export-cpf': {
    id: 'financial-export-cpf',
    title: 'Exportação com CPF do Pagador',
    category: 'financeiro',
    description: 'Gera relatórios em Excel/CSV incluindo obrigatoriamente o CPF do titular pagador de cada sessão ou avaliação.',
    clinicalAndLegalTip: 'Exigência da Receita Federal na DMED e no Carnê-Leão: sem o CPF do responsável financeiro, o paciente não pode abater os gastos com psicoterapia na declaração de IRPF.',
    bestPractice: 'Certifique-se de que o CPF do paciente ou do responsável legal esteja preenchido na ficha cadastral antes de exportar.',
    iconName: 'Download',
  },
  'patient-quick-settle': {
    id: 'patient-quick-settle',
    title: 'Baixa e Quitação Rápida de Sessões',
    category: 'financeiro',
    description: 'Permite registrar o pagamento de sessões passadas ou pacotes futuros, com seleção múltipla e emissão de recibo.',
    clinicalAndLegalTip: 'Mantém a adimplência atualizada e atualiza os indicadores de saúde financeira do paciente em tempo real.',
    bestPractice: 'Selecione a forma de pagamento correta (PIX, Cartão, Boleto) para a conciliação bancária precisa.',
    iconName: 'CheckSquare',
  },
  'avaliacao-nova': {
    id: 'avaliacao-nova',
    title: 'Abertura & Contratação de Nova Avaliação',
    category: 'avaliacao',
    description: 'Abre o formulário estruturado para formalizar a contratação do pacote de avaliação neuropsicológica, com cronograma de sessões e parcelamento financeiro.',
    howToUse: 'Selecione o paciente, o número previsto de sessões (anamnese, testagem e devolutiva), defina o valor total e o plano de parcelamento.',
    clinicalAndLegalTip: 'O contrato de avaliação neuropsicológica exige definição clara dos objetivos e do enquadre pericial nos termos da Resolução CFP nº 06/2019.',
    bestPractice: 'Sempre colete a assinatura do contrato antes de iniciar a primeira sessão de testagem com instrumentos privativos.',
    iconName: 'Plus',
  },
  'avaliacao-recibo': {
    id: 'avaliacao-recibo',
    title: 'Emissão de Recibo da Avaliação',
    category: 'financeiro',
    description: 'Gera o recibo oficial de honorários da avaliação neuropsicológica com selo de autenticidade e discriminação de parcelas.',
    howToUse: 'Clique para visualizar, imprimir ou baixar o comprovante timbrado de quitação da avaliação para entrega ao paciente ou convênio.',
    clinicalAndLegalTip: 'Em conformidade com as normas tributárias e a DMED: discrimina claramente o CPF do pagador e do paciente beneficiário.',
    bestPractice: 'Entregue o recibo após a quitação de cada parcela ou lote para viabilizar o reembolso do paciente junto a planos de saúde.',
    iconName: 'Receipt',
  },
  'avaliacao-editar': {
    id: 'avaliacao-editar',
    title: 'Edição de Dados e Plano Financeiro da Avaliação',
    category: 'avaliacao',
    description: 'Permite ajustar o plano de parcelas, datas de vencimento, demanda clínica inicial e hipóteses diagnósticas da avaliação em andamento.',
    howToUse: 'Revise os valores negociados, altere datas ou adicione observações clínicas complementares.',
    clinicalAndLegalTip: 'Alterações no escopo ou acréscimo de sessões de testagem devem ser acordadas formalmente com o paciente ou responsáveis.',
    bestPractice: 'Mantenha o registro de parcelas atualizado para sincronizar o fluxo com o módulo Financeiro e emissão de NFS-e.',
    iconName: 'Pencil',
  },
  'avaliacao-ver-prontuario': {
    id: 'avaliacao-ver-prontuario',
    title: 'Acesso Direto ao Prontuário do Paciente',
    category: 'prontuario',
    description: 'Abre instantaneamente o prontuário clínico individual do paciente na aba de Avaliações e Laudos.',
    howToUse: 'Clique para consultar o histórico completo de evoluções, documentos emitidos, contatos de responsáveis e dados cadastrais.',
    clinicalAndLegalTip: 'O acesso aos registros clínicos é restrito ao psicólogo responsável e protegido pelo sigilo profissional (Código de Ética do Psicólogo e Art. 11 da LGPD).',
    bestPractice: 'Utilize para cruzar o laudo atual com evoluções de acompanhamentos psicológicos anteriores.',
    iconName: 'ExternalLink',
  },
  'avaliacao-busca-filtro': {
    id: 'avaliacao-busca-filtro',
    title: 'Busca Rápida de Avaliações',
    category: 'avaliacao',
    description: 'Localiza avaliações ativas ou concluídas filtrando por nome do paciente, CPF ou hipótese diagnóstica preliminar (ex: TDAH, TEA, Idoso).',
    howToUse: 'Digite parte do nome, CPF ou termo clínico para filtrar a tabela em tempo real.',
    clinicalAndLegalTip: 'A busca opera em ambiente seguro e criptografado para garantir a privacidade dos pacientes atendidos.',
    bestPractice: 'Você pode digitar siglas como "TDAH" para localizar todos os pacientes em processo de avaliação para essa queixa.',
    iconName: 'Search',
  },
  'avaliacao-filtro-status': {
    id: 'avaliacao-filtro-status',
    title: 'Filtro por Fase da Avaliação',
    category: 'avaliacao',
    description: 'Segmenta as avaliações pelo estágio do processo pericial: Em Teste (aplicação de baterias), Aguardando Devolutiva (laudo em redação) ou Concluído (Laudo Emitido).',
    howToUse: 'Selecione a fase desejada para priorizar entregas e agendamento de sessões finais de orientação familiar.',
    clinicalAndLegalTip: 'Ajuda a cumprir os prazos acordados com médicos solicitantes, escolas e operadoras de saúde.',
    bestPractice: 'Revise semanalmente os pacientes com status "Aguardando Devolutiva" para finalizar a redação do laudo tempestivamente.',
    iconName: 'Filter',
  },
};
