/**
 * Synapsis Academy — Mock Data Store (Clínica Modelo "Synapsis Demo")
 * Dados 100% fictícios para garantir o isolamento absoluto da clínica real.
 */

export const MOCK_SANDBOX_CLINIC = {
  id: 9999,
  clinic_name: 'Clínica Escola Synapsis (Modo Simulação)',
  cnpj: '00.000.000/0001-99',
  phone: '(11) 99999-0000',
  email: 'treinamento@synapsisclinico.com.br',
  default_session_price: 180.0,
  default_evaluation_price: 2400.0,
};

export const MOCK_SANDBOX_PATIENTS = [
  {
    id: 901,
    full_name: 'Carlos Eduardo Rocha (Simulação)',
    preferred_name: 'Carlos Rocha',
    cpf: '111.222.333-44',
    phone: '(11) 98888-1111',
    email: 'carlos.simulacao@synapsis.com',
    birth_date: '1988-04-12',
    is_minor: 0,
    psychologist_id: 1,
    status: 'ACTIVE',
    emergency_contact: 'Mariana Rocha (Esposa) - (11) 98888-2222',
    notes: 'Paciente modelo para treinamento de prontuário e evolução CFP 06/2019.',
  },
  {
    id: 902,
    full_name: 'Ana Paula Mendonça (Simulação)',
    preferred_name: 'Ana Paula',
    cpf: '222.333.444-55',
    phone: '(11) 97777-2222',
    email: 'anapaula.simulacao@synapsis.com',
    birth_date: '1995-09-20',
    is_minor: 0,
    psychologist_id: 1,
    status: 'ACTIVE',
    emergency_contact: 'Roberto Mendonça (Pai) - (11) 97777-3333',
    notes: 'Paciente modelo para aplicação e leitura de escalas PHQ-9 e GAD-7.',
  },
  {
    id: 903,
    full_name: 'Gabriel Martins Santos (Menor / Simulação)',
    preferred_name: 'Gabrielzinho',
    cpf: '333.444.555-66',
    phone: '(11) 96666-3333',
    email: 'responsavel.gabriel@synapsis.com',
    birth_date: '2016-06-15',
    is_minor: 1,
    financial_responsible_name: 'Patrícia Martins Santos (Mãe)',
    financial_responsible_cpf: '444.555.666-77',
    financial_responsible_phone: '(11) 96666-4444',
    psychologist_id: 1,
    status: 'ACTIVE',
    notes: 'Paciente menor de idade para teste de roteamento de cobrança via responsável financeiro.',
  },
  {
    id: 904,
    full_name: 'Beatriz Vasconcelos (Simulação)',
    preferred_name: 'Bia',
    cpf: '555.666.777-88',
    phone: '(11) 95555-4444',
    email: 'beatriz.simulacao@synapsis.com',
    birth_date: '2001-11-03',
    is_minor: 0,
    psychologist_id: 1,
    status: 'ACTIVE',
    notes: 'Paciente com honorários pendentes para simulação de cobrança via WhatsApp.',
  },
];

export const MOCK_SANDBOX_BILLINGS = [
  {
    id: 801,
    patient_id: 904,
    patient_name: 'Beatriz Vasconcelos (Simulação)',
    session_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 180.0,
    status: 'PENDING',
    payment_method: 'PIX',
    whatsapp_recipient_name: 'Beatriz Vasconcelos',
    whatsapp_phone: '(11) 95555-4444',
    days_overdue: 5,
    message_preview:
      'Olá Beatriz, tudo bem? Lembramos que a sessão do dia ' +
      new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toLocaleDateString('pt-BR') +
      ' no valor de R$ 180,00 está pendente de acerto. Segue a chave PIX da clínica para pagamento.',
  },
  {
    id: 802,
    patient_id: 903,
    patient_name: 'Gabriel Martins Santos (Menor / Simulação)',
    session_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 180.0,
    status: 'PENDING',
    payment_method: 'PIX',
    whatsapp_recipient_name: 'Patrícia Martins Santos (Mãe)',
    whatsapp_phone: '(11) 96666-4444',
    days_overdue: 8,
    message_preview:
      'Olá Patrícia, tudo bem? Notamos uma pendência referente à sessão de psicoterapia do Gabriel no valor de R$ 180,00. Segue o código PIX para regularização.',
  },
  {
    id: 803,
    patient_id: 901,
    patient_name: 'Carlos Eduardo Rocha (Simulação)',
    session_date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 180.0,
    status: 'PENDING',
    payment_method: 'BOLETO',
    whatsapp_recipient_name: 'Carlos Eduardo Rocha',
    whatsapp_phone: '(11) 98888-1111',
    days_overdue: 12,
    message_preview:
      'Prezado Carlos, verificamos que seu honorário de R$ 180,00 venceu há 12 dias. Para sua comodidade, enviamos a 2ª via atualizada.',
  },
];

export const MOCK_SANDBOX_SESSIONS = [
  {
    id: 701,
    patient_id: 901,
    patient_name: 'Carlos Eduardo Rocha (Simulação)',
    psychologist_name: 'Dr. Marcos Silveira',
    room_name: 'Consultório 1 (Adulto)',
    start_time: '14:00',
    end_time: '14:50',
    status: 'CONFIRMED',
    modality: 'PRESENTIAL',
  },
  {
    id: 702,
    patient_id: 902,
    patient_name: 'Ana Paula Mendonça (Simulação)',
    psychologist_name: 'Dr. Marcos Silveira',
    room_name: 'Consultório 1 (Adulto)',
    start_time: '15:00',
    end_time: '15:50',
    status: 'WAITING_IN_LOBBY',
    modality: 'PRESENTIAL',
  },
  {
    id: 703,
    patient_id: 904,
    patient_name: 'Beatriz Vasconcelos (Simulação)',
    psychologist_name: 'Dr. Marcos Silveira',
    room_name: 'Consultório Online 1',
    start_time: '16:00',
    end_time: '16:50',
    status: 'SCHEDULED',
    modality: 'ONLINE',
  },
];

export const MOCK_SANDBOX_SCALES = [
  {
    id: 601,
    patient_id: 902,
    patient_name: 'Ana Paula Mendonça (Simulação)',
    psychologist_id: 1,
    scale_type: 'GAD7' as const,
    answers: { q1: 2, q2: 2, q3: 1, q4: 2, q5: 1, q6: 2, q7: 1 },
    total_score: 11,
    severity: 'Ansiedade Moderada',
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 602,
    patient_id: 901,
    patient_name: 'Carlos Eduardo Rocha (Simulação)',
    psychologist_id: 1,
    scale_type: 'PHQ9' as const,
    answers: { q1: 1, q2: 1, q3: 2, q4: 1, q5: 0, q6: 1, q7: 0, q8: 0, q9: 0 },
    total_score: 6,
    severity: 'Depressão Leve',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_SANDBOX_CARNE_LEAO = {
  psychologist: {
    id: 1,
    name: 'Dr. Marcos Silveira (Simulação)',
    crp: '06/123456',
    cpf: '123.456.789-00',
    cboCode: '2515-10',
  },
  competence: {
    year: new Date().getFullYear(),
    month: new Date().getMonth() + 1,
    label: new Date().toLocaleDateString('pt-BR', { month: 'long', year: 'numeric' }),
  },
  settings: {
    user_id: 1,
    inss_mode: 'STANDARD_20' as const,
    inss_custom_amount: 0,
    dependents_count: 0,
    use_simplified_deduction: 0,
  },
  totalRevenues: 4800.0,
  totalDeductibleExpenses: 1100.0,
  coworkingRoomDeductions: 0,
  carriedOverDeficitFromPreviousMonths: 0,
  netLivroCaixaBalance: 3700.0,
  nextMonthCarryOverDeficit: 0,
  inssDeduction: 282.4,
  dependentsDeduction: 0,
  totalPersonalDeductions: 282.4,
  totalCombinedDeductions: 1382.4,
  taxBase: 3417.6,
  darf: {
    taxableAmount: 3417.6,
    aliquotPercent: 15.0,
    deductionParcel: 370.4,
    calculatedTax: 142.24,
    isBelowMinThreshold: false,
    finalDarfAmount: 142.24,
    revenueCode: '0190',
    dueDate: '2026-10-31',
    dueDateFormatted: '31/10/2026',
    notes: 'Apuração Simulação Sandbox Synapsis Academy',
  },
  revenues: [
    {
      id: 801,
      date: new Date().toISOString().split('T')[0],
      amount: 180.0,
      patientId: 904,
      patientName: 'Beatriz Vasconcelos (Simulação)',
      patientCpf: '555.666.777-88',
      payerName: 'Beatriz Vasconcelos',
      payerCpf: '555.666.777-88',
      cboCode: '2515-10',
      description: 'Sessão de Psicoterapia Individual',
      receiptNumber: 'REC-2026-0801',
    },
    {
      id: 802,
      date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      amount: 180.0,
      patientId: 901,
      patientName: 'Carlos Eduardo Rocha (Simulação)',
      patientCpf: '111.222.333-44',
      payerName: 'Carlos Eduardo Rocha',
      payerCpf: '111.222.333-44',
      cboCode: '2515-10',
      description: 'Sessão de Psicoterapia Individual',
      receiptNumber: 'REC-2026-0802',
    },
  ],
  expenses: [
    {
      id: 501,
      date: new Date().toISOString().split('T')[0],
      amount: 850.0,
      originalAmount: 850.0,
      title: 'Sublocação de Consultório Clínico',
      category: 'ALUGUEL',
      rfbAccountCode: '3101',
      isShared: false,
      splitPercent: 100,
      origin: 'DIRECT' as const,
    },
    {
      id: 502,
      date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      amount: 250.0,
      originalAmount: 250.0,
      title: 'Anuidade do Conselho Regional de Psicologia (CRP)',
      category: 'CRP_CONSELHO',
      rfbAccountCode: '3104',
      isShared: false,
      splitPercent: 100,
      origin: 'DIRECT' as const,
    },
  ],
};

export const MOCK_SANDBOX_DOSSIER = {
  ...MOCK_SANDBOX_CARNE_LEAO,
};
